#!/usr/bin/env python3
"""
CloudIntel local demo store.

A tiny HTTP server that serves synthetic responses reproducing the real signals every
CloudIntel fingerprint looks for (headers, error XML, cookies). Point Burp Suite at it as
a proxy target, load the CloudIntel extension, then run `drive.py` (or curl commands from
its docs) to exercise all 40 fingerprints locally — no internet, no real cloud accounts.

Routing:
- The server keys off the request's `Host:` header, not the connection target. That way you
  can send requests to `http://127.0.0.1:8787/` while using a real cloud hostname in `Host:`
  (via `curl --resolve` or Burp's target overrides), and CloudIntel sees the genuine host.
- Alternatively, hit `/<service>/...` directly — the URL path selects the response as a
  fallback when the Host header is generic.

Usage:
    python3 server.py                 # http://127.0.0.1:8787
    python3 server.py --port 9000     # custom port
    python3 drive.py                  # optional: fire every scenario through Burp
"""

import argparse
import http.server
import re
import socketserver
import sys
from typing import Callable

# --- Response registry --------------------------------------------------------

# Each entry: (host regex, url-path regex, handler(name)->(status, headers, body))
# The first matching entry wins.
Handler = Callable[[str], tuple]  # (status, headers dict, body str)

SCENARIOS: list[tuple[re.Pattern, re.Pattern, Handler]] = []


def scenario(host_pat: str, path_pat: str = ".*"):
    def deco(fn):
        SCENARIOS.append((re.compile(host_pat, re.I), re.compile(path_pat, re.I), fn))
        return fn
    return deco


# ---------- AWS ---------------------------------------------------------------

@scenario(r".*\.s3\.amazonaws\.com$", r".*")
def s3(path):
    body = (
        '<?xml version="1.0" encoding="UTF-8"?>'
        '<Error><Code>NoSuchBucket</Code>'
        '<Message>The specified bucket does not exist</Message>'
        '<BucketName>demo-bucket</BucketName></Error>'
    )
    return 404, {
        "Server": "AmazonS3",
        "x-amz-request-id": "SYNTH123",
        "x-amz-id-2": "abc/def+xyz==",
        "x-amz-bucket-region": "us-east-1",
        "Content-Type": "application/xml",
    }, body


@scenario(r".*\.cloudfront\.net$")
def cloudfront(path):
    body = ("<html><body><h1>ERROR: The request could not be satisfied</h1>"
            "<p>Generated by cloudfront (CloudFront)</p></body></html>")
    return 403, {
        "Server": "CloudFront",
        "Via": "1.1 abcdef.cloudfront.net (CloudFront)",
        "x-amz-cf-id": "SYNTH_CF_ID==",
        "x-amz-cf-pop": "IAD53-C1",
        "X-Cache": "Error from cloudfront",
        "Content-Type": "text/html",
    }, body


@scenario(r".*\.execute-api\.[a-z0-9-]+\.amazonaws\.com$")
def apigw(path):
    body = '{"message":"Missing Authentication Token"}'
    return 403, {
        "x-amzn-requestid": "SYNTH-APIGW",
        "x-amzn-errortype": "MissingAuthenticationTokenException",
        "x-amz-apigw-id": "abc=",
        "x-amzn-trace-id": "Root=1-abcd",
        "Content-Type": "application/json",
    }, body


@scenario(r".*\.lambda-url\.[a-z0-9-]+\.on\.aws$")
def lambda_url(path):
    body = '{"message":"Forbidden"}'
    return 403, {
        "x-amzn-requestid": "SYNTH-LAMBDA",
        "x-amzn-remapped-content-length": "0",
        "x-amzn-trace-id": "Root=1-xyz",
        "Content-Type": "application/json",
    }, body


@scenario(r"cognito-idp\.[a-z0-9-]+\.amazonaws\.com$")
def cognito(path):
    body = '{"__type":"NotAuthorizedException","message":"Access Token has expired"}'
    return 400, {
        "x-amzn-requestid": "SYNTH-COG",
        "x-amzn-errortype": "NotAuthorizedException:",
        "Content-Type": "application/x-amz-json-1.1",
    }, body


@scenario(r".*\.elasticbeanstalk\.com$")
def beanstalk(path):
    body = "<html><body>Elastic Beanstalk default page</body></html>"
    return 200, {"Server": "nginx", "X-ElasticBeanstalk-Origin": "yes",
                 "Content-Type": "text/html"}, body


@scenario(r".*\.elb\.amazonaws\.com$")
def elb(path):
    return 200, {"Server": "awselb/2.0",
                 "Set-Cookie": "AWSALB=SYNTH; Path=/",
                 "Content-Type": "text/plain"}, "ok"


@scenario(r"ec2-[0-9\-]+\.[a-z0-9-]*compute-?1?\.amazonaws\.com$")
def ec2(path):
    return 200, {"Server": "Apache/2.4.6", "Content-Type": "text/html"}, "<html>EC2 host</html>"


@scenario(r"[0-9]+\.dkr\.ecr\.[a-z0-9-]+\.amazonaws\.com$", r"/v2/?")
def ecr(path):
    return 401, {
        "Docker-Distribution-Api-Version": "registry/2.0",
        "WWW-Authenticate": 'Bearer realm="https://123456789012.dkr.ecr.us-east-1.amazonaws.com/token"',
        "Content-Type": "application/json",
    }, '{"errors":[{"code":"UNAUTHORIZED"}]}'


@scenario(r"sns\.[a-z0-9-]+\.amazonaws\.com$")
def sns(path):
    body = ('<?xml version="1.0" encoding="UTF-8"?>'
            '<ErrorResponse xmlns="http://sns.amazonaws.com/doc/2010-03-31/">'
            '<Error><Code>InvalidAction</Code></Error></ErrorResponse>')
    return 400, {"x-amzn-requestid": "SYNTH-SNS",
                 "Content-Type": "text/xml"}, body


@scenario(r"sqs\.[a-z0-9-]+\.amazonaws\.com$")
def sqs(path):
    body = ('<?xml version="1.0"?><ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/">'
            '<Error><Code>AccessDenied</Code></Error></ErrorResponse>')
    return 403, {"x-amzn-requestid": "SYNTH-SQS",
                 "Content-Type": "text/xml"}, body


@scenario(r"route53\.amazonaws\.com$")
def route53(path):
    body = ('<?xml version="1.0"?><ErrorResponse><Error>'
            '<Code>InvalidClientTokenId</Code></Error></ErrorResponse>')
    return 403, {"x-amzn-requestid": "SYNTH-R53",
                 "Content-Type": "text/xml"}, body


# ---------- Azure -------------------------------------------------------------

@scenario(r".*\.blob\.core\.windows\.net$")
def azure_blob(path):
    body = ('<?xml version="1.0" encoding="utf-8"?><Error>'
            '<Code>BlobNotFound</Code><Message>The specified blob does not exist.</Message></Error>')
    return 404, {
        "Server": "Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0",
        "x-ms-version": "2021-08-06",
        "x-ms-request-id": "SYNTH-BLOB",
        "Content-Type": "application/xml",
    }, body


@scenario(r".*\.azurewebsites\.net$")
def azure_func(path):
    body = "<html><body>Your Functions 4.0 app is up and running.</body></html>"
    return 200, {
        "Set-Cookie": "ARRAffinity=SYNTHAFFINITY; Path=/",
        "X-Powered-By": "ASP.NET",
        "Content-Type": "text/html",
    }, body


@scenario(r".*\.azureedge\.net$")
def azure_cdn(path):
    return 200, {"X-Azure-Ref": "0SYNTHREF", "x-msedge-ref": "SYNTHEDGE",
                 "Content-Type": "text/html"}, "<html>cdn</html>"


@scenario(r".*\.documents\.azure\.com$")
def cosmos(path):
    return 401, {"x-ms-request-charge": "1.0", "x-ms-activity-id": "SYNTHACT",
                 "x-ms-gatewayversion": "1.0", "Content-Type": "application/json"}, \
        '{"code":"Unauthorized","message":"Required Header authorization is missing."}'


@scenario(r".*\.queue\.core\.windows\.net$")
def azq(path):
    body = ('<?xml version="1.0" encoding="utf-8"?><Error>'
            '<Code>QueueNotFound</Code></Error>')
    return 404, {"Server": "Windows-Azure-Queue/1.0 Microsoft-HTTPAPI/2.0",
                 "x-ms-request-id": "SYNTH-Q", "x-ms-version": "2021-08-06",
                 "Content-Type": "application/xml"}, body


@scenario(r".*\.file\.core\.windows\.net$")
def azf(path):
    body = ('<?xml version="1.0" encoding="utf-8"?><Error>'
            '<Code>ShareNotFound</Code></Error>')
    return 404, {"Server": "Windows-Azure-File Server/1.0 Microsoft-HTTPAPI/2.0",
                 "x-ms-request-id": "SYNTH-F", "x-ms-version": "2021-08-06",
                 "Content-Type": "application/xml"}, body


@scenario(r".*\.vault\.azure\.net$")
def keyvault(path):
    return 401, {
        "WWW-Authenticate": 'Bearer authorization="https://login.windows.net/x", resource="https://vault.azure.net"',
        "x-ms-keyvault-region": "eastus",
        "x-ms-keyvault-service-version": "1.9",
        "x-ms-keyvault-network-info": "conn_type=Ipv4;addr=1.2.3.4;",
        "Content-Type": "application/json",
    }, '{"error":{"code":"Unauthorized"}}'


# ---------- Google Cloud ------------------------------------------------------

@scenario(r"storage\.googleapis\.com$")
def gcs(path):
    body = ('<?xml version="1.0"?><Error><Code>NoSuchBucket</Code>'
            '<Message>The specified bucket does not exist.</Message></Error>')
    return 404, {"x-goog-generation": "1", "x-goog-metageneration": "1",
                 "x-goog-storage-class": "STANDARD", "x-guploader-uploadid": "SYNTH",
                 "Content-Type": "application/xml"}, body


@scenario(r".*\.cloudfunctions\.net$")
def gcf(path):
    return 403, {"Server": "Google Frontend", "x-cloud-trace-context": "abc/1",
                 "Content-Type": "application/json"}, '{"error":"Forbidden"}'


@scenario(r".*\.firebaseio\.com$")
def firebase_rtdb(path):
    return 401, {"Content-Type": "application/json"}, \
        '{"error":"Permission denied"}'


@scenario(r"firebasestorage\.googleapis\.com$")
def firebase_storage(path):
    return 403, {"Content-Type": "application/json",
                 "x-goog-storage-class": "STANDARD"}, \
        '{"error":{"code":403,"message":"Permission denied. Firebase Storage rules"}}'


@scenario(r".*\.appspot\.com$")
def appengine(path):
    return 200, {"Server": "Google Frontend", "x-cloud-trace-context": "1/2",
                 "Content-Type": "text/html"}, "<html>appengine</html>"


@scenario(r".*\.run\.app$")
def cloudrun(path):
    return 403, {"Server": "Google Frontend", "x-cloud-trace-context": "3/4",
                 "Content-Type": "application/json"}, '{"error":"Forbidden"}'


@scenario(r"bigquery\.googleapis\.com$")
def bq(path):
    return 401, {"Content-Type": "application/json",
                 "x-cloud-trace-context": "5/6"}, '{"error":{"code":401}}'


@scenario(r"pubsub\.googleapis\.com$")
def pubsub(path):
    return 401, {"Content-Type": "application/json",
                 "x-cloud-trace-context": "7/8"}, '{"error":{"code":401}}'


# ---------- Others ------------------------------------------------------------

@scenario(r".*\.digitaloceanspaces\.com$")
def do_spaces(path):
    body = ('<?xml version="1.0"?><Error><Code>NoSuchBucket</Code></Error>')
    return 404, {"Server": "AmazonS3",  # DO Spaces is S3-compatible
                 "x-amz-request-id": "SYNTH-DO",
                 "Content-Type": "application/xml"}, body


@scenario(r".*\.ondigitalocean\.app$")
def do_apps(path):
    return 200, {"Server": "cloudflare",  # front, then app; app markers vary — keep minimal
                 "X-DO-App-Origin": "yes",
                 "Content-Type": "text/html"}, "<html>DO Apps</html>"


@scenario(r".*")
def cloudflare_generic(path, host=""):
    # Only fired via fallback below when Host looks Cloudflare-fronted.
    return 200, {"Server": "cloudflare", "CF-RAY": "8abcd1234ef-IAD",
                 "CF-Cache-Status": "DYNAMIC",
                 "Content-Type": "text/html"}, "<html>cf</html>"


@scenario(r".*\.fastly\.net$|.*\.fastlylb\.net$")
def fastly(path):
    return 500, {"Server": "Varnish", "Via": "1.1 varnish",
                 "X-Served-By": "cache-iad-kiad7000123-IAD",
                 "X-Timer": "S1234.567890,VS0,VE1",
                 "Content-Type": "text/html"}, \
        "Fastly error: unknown domain: example. Please check that this domain has been added to a service."


@scenario(r".*\.akamaized\.net$|.*\.akamaihd\.net$|.*\.akamaitechnologies\.com$")
def akamai(path):
    return 200, {"Server": "AkamaiGHost", "X-Akamai-Transformed": "9 0 0 pmb=mRUM,1",
                 "X-Akamai-Request-ID": "SYNTH-AK",
                 "Content-Type": "text/html"}, "<html>akamai</html>"


@scenario(r".*\.vercel\.app$")
def vercel(path):
    return 200, {"Server": "Vercel", "x-vercel-id": "iad1::SYNTH",
                 "x-vercel-cache": "MISS", "Content-Type": "text/html"}, "<html>vercel</html>"


@scenario(r".*\.netlify\.app$")
def netlify(path):
    return 200, {"Server": "Netlify",
                 "x-nf-request-id": "01SYNTHREQ",
                 "Content-Type": "text/html"}, "<html>netlify</html>"


@scenario(r".*\.github\.io$")
def gh_pages(path):
    return 200, {"Server": "GitHub.com",
                 "x-github-request-id": "SYNTH:GH",
                 "Content-Type": "text/html"}, "<html>ghpages</html>"


@scenario(r".*\.herokuapp\.com$")
def heroku(path):
    return 200, {"Server": "Cowboy",
                 "Via": "1.1 vegur",
                 "X-Request-Id": "SYNTH-HEROKU",
                 "Content-Type": "text/html"}, "<html>heroku</html>"


@scenario(r".*\.oraclecloud\.com$|objectstorage\.[a-z0-9-]+\.oraclecloud\.com$")
def oci(path):
    return 404, {"opc-request-id": "SYNTH-OCI",
                 "opc-service-name": "objectstorage",
                 "Content-Type": "application/json"}, '{"code":"BucketNotFound"}'


@scenario(r".*\.aliyuncs\.com$")
def alioss(path):
    body = ('<?xml version="1.0" encoding="UTF-8"?><Error>'
            '<Code>NoSuchBucket</Code></Error>')
    return 404, {"Server": "AliyunOSS",
                 "x-oss-request-id": "SYNTH-OSS",
                 "Content-Type": "application/xml"}, body


@scenario(r".*\.wasabisys\.com$")
def wasabi(path):
    body = ('<?xml version="1.0"?><Error><Code>NoSuchBucket</Code></Error>')
    return 404, {"Server": "WasabiS3/1.0", "x-amz-request-id": "SYNTH-WAS",
                 "Content-Type": "application/xml"}, body


@scenario(r".*\.backblazeb2\.com$")
def b2(path):
    return 401, {"Server": "AmazonS3",
                 "x-bz-request-id": "SYNTH-B2",
                 "Content-Type": "application/json"}, '{"code":"unauthorized"}'


@scenario(r".*\.b-cdn\.net$")
def bunnycdn(path):
    return 200, {"Server": "BunnyCDN-DE1-1234",
                 "CDN-Cache": "HIT",
                 "CDN-EdgeStorageId": "1234",
                 "CDN-PullZone": "1234",
                 "Content-Type": "text/html"}, "<html>bunny</html>"


# --- Server -------------------------------------------------------------------

def dispatch(host: str, path: str):
    """Return (status, headers, body) for the first matching scenario."""
    for host_re, path_re, fn in SCENARIOS:
        if host_re.match(host) and path_re.match(path):
            return fn(path)
    # Cloudflare-fronted heuristic (only if host contains 'cf' or explicit path).
    if "cloudflare" in host.lower() or path.startswith("/cloudflare"):
        return cloudflare_generic(path)
    return 200, {"Content-Type": "text/plain"}, "cloudintel demo store: no matching scenario for host " + host


class Handler(http.server.BaseHTTPRequestHandler):
    def _handle(self):
        host = self.headers.get("Host", "")
        # Strip port from host header.
        if ":" in host and not host.startswith("["):
            host = host.split(":", 1)[0]
        status, headers, body = dispatch(host, self.path)
        self.send_response(status)
        for k, v in headers.items():
            self.send_header(k, v)
        self.send_header("Content-Length", str(len(body.encode("utf-8"))))
        self.end_headers()
        self.wfile.write(body.encode("utf-8"))

    def do_GET(self):
        self._handle()

    def do_HEAD(self):
        self._handle()

    def log_message(self, fmt, *args):
        sys.stderr.write("%s - %s\n" % (self.address_string(), fmt % args))


class ReuseTCPServer(socketserver.ThreadingTCPServer):
    allow_reuse_address = True


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--port", type=int, default=8787)
    p.add_argument("--host", default="127.0.0.1")
    args = p.parse_args()
    server = ReuseTCPServer((args.host, args.port), Handler)
    print(f"CloudIntel demo store listening on http://{args.host}:{args.port}")
    print(f"Registered scenarios: {len(SCENARIOS)}")
    print("Tip: run drive.py to fire every scenario through Burp automatically.")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        server.shutdown()


if __name__ == "__main__":
    main()
